In [1]:
import numpy as np
import torch

print(np.__version__)
print(torch.__version__)

x = torch.tensor([1,2,3])
print(x)


2.2.6
2.10.0+cpu
tensor([1, 2, 3])


In [2]:
import torch 
x = torch.tensor([2,1,3,4])
print(x)

tensor([2, 1, 3, 4])


In [7]:
i = torch.tensor([20,30,40,50])
print(i[0])
print(i[1])

d_2 = torch.tensor([
    [10,20,30],
    [20,40,60]
])
print(d_2[0,1])
print(d_2[1,2])
    

tensor(20)
tensor(30)
tensor(20)
tensor(60)


In [9]:
a = torch.tensor([20,30,10])
b = torch.tensor([1, 5, 7])
print(a+b)
print(a*b)

tensor([21, 35, 17])
tensor([ 20, 150,  70])


In [12]:
import numpy as np
arr = np.array([1,2,3])
n = torch.from_numpy(arr)

In [14]:
import torch
#setup input data x
x = torch.tensor([1.,2.,3.,4.])
#setup input data y
y = torch.tensor([2.,4.,6.,8.])
 #wrong guesses w and b
w = torch.tensor(0.0)
b = torch.tensor(0.0)

#setup 4
y_pred= w * x + b

loss = ((y_pred - y) **2).mean()
print("predict value", y_pred)
print("actual value", y)
print("loss",loss)

predict value tensor([0., 0., 0., 0.])
actual value tensor([2., 4., 6., 8.])
loss tensor(30.)
